import { CreateUserController } from './users/CreateUserController';
import { AuthUserController } from './users/AuthUserController';
import { LogoutController } from './users/LogoutController';
import { DeleteUserController } from './users/DeleteUserController';
import { UpdateUserController } from './users/UpdateUserController';
import { ChangePswController } from './users/ChangePswController';
import { ListarUserDadosController } from './users/ListarUserDadosController';
import { GetMediaController } from './media/GetMediaController';
import { UploadMediaController } from './media/UploadMediaController';
import { CriarTarefasController } from './tarefas/CriarTarefasController';
import { ListarTarefasController } from './tarefas/ListarTarefasController';
import { EditarTarefasController } from './tarefas/EditarTarefasController';
import { DeletarTarefasController } from './tarefas/DeletarTarefasController';
import { CriarNegociacoesController } from './negociacao/CriarNegociacoesController';
import { ListarNegociacoesController } from './negociacao/ListarNegociacoesController';
import { EditarNegociacoesController } from './negociacao/EditarNegociacoesController';
import { DeletarNegociacoesController } from './negociacao/DeletarNegociacoesController';
import { CriarClientePFController } from './clientes/CriarClientePFController';
import { EditarClientePFController } from './clientes/EditarClientePFController';
import { DeletarClientePFController } from './clientes/DeletarClientePFController';
import { CriarClientePJController } from './clientes/CriarClientePJController';
import { EditarClientePJController } from './clientes/EditarClientePJController';
import { DeletarClientePJController } from './clientes/DeletarClientePJController';
import { CriarSeguradorasController } from './seguradoras/CriarSeguradorasController';
import { EditarSeguradorasController } from './seguradoras/EditarSeguradorasController';
import { DeletarSeguradorasController } from './seguradoras/DeletarSeguradorasController';
import { ListarSeguradorasController } from './seguradoras/ListarSeguradorasController';
import { ListarClienteController } from './clientes/ListarClienteController';
import { CriarContatoNegociacaoController } from './negociacao/CriarContatoNegociacaoController';
import { DeletarContatoNegociacaoController } from './negociacao/DeletarContatoNegociacaoController';
import { DeletarPropostaNegociacaoController } from './negociacao/DeletarPropostaNegociacaoController';
import { EditarContatoNegociacaoController } from './negociacao/EditarContatoNegociacaoController';
import { EditarPropostaNegociacaoController } from './negociacao/EditarPropostaNegociacaoController';
import { ListarPropostaNegociacaoController } from './negociacao/ListarPropostaNegociacaoController';
import { CriarPropostaNegociacaoController } from './negociacao/CriarPropostaNegociacaoController';
import { DashboardController } from './users/DashboardController';
import { GerarCodPswController } from './users/GerarCodPswController';
import { VerificarCodigoController } from './users/VerificarCodigoController';
import { ListarNotificacoesController } from './ListarNotificacoesController';
import { CriarAnotacaoController } from './anotacao/CriarAnotacaoController';
import { DeletarAnotacaoController } from './anotacao/DeletarAnotacaoController';
import { EditarAnotacaoController } from './anotacao/EditarAnotacaoController';
import { ListarAnotacaoController } from './anotacao/ListarAnotacaoController';




import { CreateUserService } from '../services/users/CreateUserService';
import { AuthUserService } from '../services/users/AuthUserService';
import { LogoutService } from '../services/users/LogoutService';
import { DeleteUserService } from '../services/users/DeleteUserService';
import { UpdateUserService } from '../services/users/UpdateUserService';
import { ChangePswService } from '../services/users/ChangePswService';
import { ListarUserDadosService } from '../services/users/ListarUserDadosService';
import { GetMediaService } from '../services/media/GetMediaService';
import { UploadMediaService } from '../services/media/UploadMediaService';
import { CriarTarefasService } from '../services/tarefas/CriarTarefasService';
import { ListarTarefasService } from '../services/tarefas/ListarTarefasService';
import { EditarTarefasService } from '../services/tarefas/EditarTarefasService';
import { DeletarTarefasService } from '../services/tarefas/DeletarTarefasService';
import { CriarNegociacoesService } from '../services/negociacao/CriarNegociacoesService';
import { ListarNegociacoesService } from '../services/negociacao/ListarNegociacoesService';
import { EditarNegociacoesService } from '../services/negociacao/EditarNegociacoesService';
import { DeletarNegociacoesService } from '../services/negociacao/DeletarNegociacoesService';
import { CriarClientePFService } from '../services/clientes/CriarClientePFService';
import { EditarClientePFService } from '../services/clientes/EditarClientePFService';
import { DeletarClientePFService } from '../services/clientes/DeletarClientePFService';
import { CriarClientePJService } from '../services/clientes/CriarClientePJService';
import { EditarClientePJService } from '../services/clientes/EditarClientePJService';
import { DeletarClientePJService } from '../services/clientes/DeletarClientePJService';
import { ListarClienteService } from '../services/clientes/ListarClienteService';
import { CriarSeguradorasService } from '../services/seguradoras/CriarSeguradorasService';
import { EditarSeguradorasService } from '../services/seguradoras/EditarSeguradorasService';
import { DeletarSeguradorasService } from '../services/seguradoras/DeletarSeguradorasService';
import { ListarSeguradorasService } from '../services/seguradoras/ListarSeguradorasService';
import { CriarContatoNegociacaoService } from '../services/negociacao/CriarContatoNegociacaoService';
import { DeletarContatoNegociacaoService } from '../services/clientes/DeletarContatoNegociacaoService';
import { DeletarPropostaNegociacaoService } from '../services/clientes/DeletarPropostaNegociacaoService';
import { EditarContatoNegociacaoService } from '../services/clientes/EditarContatoNegociacaoService';
import { EditarPropostaNegociacaoService } from '../services/negociacao/EditarPropostaNegociacaoService';
import { ListarPropostaNegociacaoService } from '../services/negociacao/ListarPropostaNegociacaoService';
import { CriarPropostaNegociacaoService } from '../services/negociacao/CriarPropostaNegociacaoService';
import { DashboardService } from '../services/users/DashboardService';
import { GerarCodPswService } from '../services/users/GerarCodPswService';
import { VerificarCodigoService } from '../services/users/VerificarCodigoService';
import { ListarNotificacoesService } from '../services/ListarNotificacoesService';
import { CriarAnotacaoService } from '../services/anotacao/CriarAnotacaoService';
import { DeletarAnotacaoService } from '../services/anotacao/DeletarAnotacaoService';
import { EditarAnotacaoService } from '../services/anotacao/EditarAnotacaoService';
import { ListarAnotacaoService } from '../services/anotacao/ListarAnotacaoService';




const createUserService = new CreateUserService();
const authUserService = new AuthUserService();
const logoutService = new LogoutService();
const deleteUserService = new DeleteUserService();
const updateUserService = new UpdateUserService();
const changePswService = new ChangePswService();
const listarUserDadosService = new ListarUserDadosService();
const getMediaService = new GetMediaService();
const uploadMediaService = new UploadMediaService();
const criarTarefasService = new CriarTarefasService();
const listarTarefasService = new ListarTarefasService();
const editarTarefasService = new EditarTarefasService();
const deletarTarefasService = new DeletarTarefasService();
const criarNegociacoesService = new CriarNegociacoesService(); 
const listarNegociacoesService = new ListarNegociacoesService();
const editarNegociacoesService = new EditarNegociacoesService();
const deletarNegociacoesService = new DeletarNegociacoesService();
const criarClientePFService = new CriarClientePFService();
const editarClientePFService = new EditarClientePFService();
const deletarClientePFService = new DeletarClientePFService();
const listarClienteService = new ListarClienteService();
const criarClientePJService = new CriarClientePJService();
const editarClientePJService = new EditarClientePJService();
const deletarClientePJService = new DeletarClientePJService();
const criarSeguradorasService = new CriarSeguradorasService();
const editarSeguradorasService = new EditarSeguradorasService();
const deletarSeguradorasService = new DeletarSeguradorasService();
const listarSeguradorasService = new ListarSeguradorasService();
const criarContatoNegociacaoService = new CriarContatoNegociacaoService();
const deletarContatoNegociacaoService = new DeletarContatoNegociacaoService();
const deletarPropostaNegociacaoService = new DeletarPropostaNegociacaoService();
const editarContatoNegociacaoService = new EditarContatoNegociacaoService();
const editarPropostaNegociacaoService = new EditarPropostaNegociacaoService();
const listarPropostaNegociacaoService = new ListarPropostaNegociacaoService(); 
const criarPropostaNegociacaoService = new CriarPropostaNegociacaoService();
const dashboardService = new DashboardService();
const gerarCodPswService = new GerarCodPswService();
const verificarCodigoService = new VerificarCodigoService();
const listarNotificacoesService = new ListarNotificacoesService();
const criarAnotacaoService = new CriarAnotacaoService();
const deletarAnotacaoService = new DeletarAnotacaoService();
const editarAnotacaoService = new EditarAnotacaoService();
const listarAnotacaoService = new ListarAnotacaoService();




export const createUserController = new CreateUserController(createUserService);
export const authUserController = new AuthUserController(authUserService);
export const logoutController = new LogoutController(logoutService);
export const deleteUserController = new DeleteUserController(deleteUserService);
export const updateUserController = new UpdateUserController(updateUserService);
export const changePswController = new ChangePswController(changePswService);
export const listarUserDadosController = new ListarUserDadosController(listarUserDadosService);
export const getMediaController = new GetMediaController(getMediaService);
export const uploadMediaController = new UploadMediaController(uploadMediaService);
export const criarTarefasController = new CriarTarefasController(criarTarefasService);
export const listarTarefasController = new ListarTarefasController(listarTarefasService);
export const editarTarefasController = new EditarTarefasController(editarTarefasService);
export const deletarTarefasController = new DeletarTarefasController(deletarTarefasService);
export const criarNegociacoesController = new CriarNegociacoesController(criarNegociacoesService);
export const listarNegociacoesController = new ListarNegociacoesController(listarNegociacoesService);
export const editarNegociacoesController = new EditarNegociacoesController(editarNegociacoesService);
export const deletarNegociacoesController = new DeletarNegociacoesController(deletarNegociacoesService);
export const criarClientePFController = new CriarClientePFController(criarClientePFService);
export const editarClientePFController = new EditarClientePFController(editarClientePFService);
export const deletarClientePFController = new DeletarClientePFController(deletarClientePFService);
export const criarClientePJController = new CriarClientePJController(criarClientePJService);
export const editarClientePJController = new EditarClientePJController(editarClientePJService);
export const deletarClientePJController = new DeletarClientePJController(deletarClientePJService);
export const listarClienteController = new ListarClienteController(listarClienteService);
export const criarSeguradorasController = new CriarSeguradorasController(criarSeguradorasService);
export const editarSeguradorasController = new EditarSeguradorasController(editarSeguradorasService);
export const deletarSeguradorasController = new DeletarSeguradorasController(deletarSeguradorasService);
export const listarSeguradorasController = new ListarSeguradorasController(listarSeguradorasService);
export const criarContatoNegociacaoController = new CriarContatoNegociacaoController(criarContatoNegociacaoService);
export const deletarContatoNegociacaoController = new DeletarContatoNegociacaoController(deletarContatoNegociacaoService);
export const deletarPropostaNegociacaoController = new DeletarPropostaNegociacaoController(deletarPropostaNegociacaoService);
export const editarPropostaNegociacaoController = new EditarPropostaNegociacaoController(editarPropostaNegociacaoService);
export const editarContatoNegociacaoController = new EditarContatoNegociacaoController(editarContatoNegociacaoService);
export const listarPropostaNegociacaoController = new ListarPropostaNegociacaoController(listarPropostaNegociacaoService);
export const criarPropostaNegociacaoController = new CriarPropostaNegociacaoController(criarPropostaNegociacaoService);
export const dashboardController = new DashboardController(dashboardService);
export const gerarCodPswController = new GerarCodPswController(gerarCodPswService);
export const verificarCodigoController = new VerificarCodigoController(verificarCodigoService);
export const listarNotificacoesController = new ListarNotificacoesController(listarNotificacoesService);
export const criarAnotacaoController = new CriarAnotacaoController(criarAnotacaoService);
export const deletarAnotacaoController = new DeletarAnotacaoController(deletarAnotacaoService);
export const editarAnotacaoController = new EditarAnotacaoController(editarAnotacaoService);
export const listarAnotacaoController = new ListarAnotacaoController( listarAnotacaoService);
